package sri.universal.styles

import sri.universal.apis.AnimatedValue

import scala.scalajs.js
import scala.scalajs.js.annotation.ScalaJSDefined
import scala.scalajs.js.|

@ScalaJSDefined
trait UniversalStyle extends js.Object {
  var flex: js.UndefOr[Double | AnimatedValue] = js.undefined
  var flexBasis: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  var flexShrink: js.UndefOr[Double | AnimatedValue] = js.undefined
  var flexGrow: js.UndefOr[Double | AnimatedValue] = js.undefined
  var borderBottomWidth: js.UndefOr[Double | AnimatedValue] = js.undefined
  var borderLeftWidth: js.UndefOr[Double | AnimatedValue] = js.undefined
  var borderRightWidth: js.UndefOr[Double | AnimatedValue] = js.undefined
  var borderTopWidth: js.UndefOr[Double | AnimatedValue] = js.undefined
  var borderWidth: js.UndefOr[Double | AnimatedValue] = js.undefined
  var bottom: js.UndefOr[Double | AnimatedValue] = js.undefined
  var height: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  var left: js.UndefOr[Double | AnimatedValue] = js.undefined
  var margin: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  var marginBottom: js.UndefOr[Double | AnimatedValue] = js.undefined
  var marginHorizontal: js.UndefOr[Double | AnimatedValue] = js.undefined
  var marginLeft: js.UndefOr[Double | AnimatedValue] = js.undefined
  var marginRight: js.UndefOr[Double | AnimatedValue] = js.undefined
  var marginTop: js.UndefOr[Double | AnimatedValue] = js.undefined
  var marginVertical: js.UndefOr[Double | AnimatedValue] = js.undefined
  var maxHeight: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  var maxWidth: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  var minHeight: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  var minWidth: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  var padding: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  var paddingBottom: js.UndefOr[Double | AnimatedValue] = js.undefined
  var paddingHorizontal: js.UndefOr[Double | AnimatedValue] = js.undefined
  var paddingLeft: js.UndefOr[Double | AnimatedValue] = js.undefined
  var paddingRight: js.UndefOr[Double | AnimatedValue] = js.undefined
  var paddingTop: js.UndefOr[Double | AnimatedValue] = js.undefined
  var paddingVertical: js.UndefOr[Double | AnimatedValue] = js.undefined
  var right: js.UndefOr[Double | AnimatedValue] = js.undefined
  var top: js.UndefOr[Double | AnimatedValue] = js.undefined
  var width: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  var zIndex: js.UndefOr[Double | AnimatedValue] = js.undefined
  var letterSpacing: js.UndefOr[Double | AnimatedValue] = js.undefined
  var overflow: js.UndefOr[String] = js.undefined
  var position: js.UndefOr[String] = js.undefined
  var flexDirection: js.UndefOr[String] = js.undefined
  var flexWrap: js.UndefOr[String] = js.undefined
  var alignItems: js.UndefOr[String] = js.undefined
  var alignSelf: js.UndefOr[String] = js.undefined
  var justifyContent: js.UndefOr[String] = js.undefined
  var color: js.UndefOr[String] = js.undefined
  var containerBackgroundColor: js.UndefOr[String] = js.undefined
  var fontFamily: js.UndefOr[String] = js.undefined
  var fontSize: js.UndefOr[Double | AnimatedValue] = js.undefined
  var lineHeight: js.UndefOr[Double | AnimatedValue] = js.undefined
  var textShadowOffset: js.UndefOr[js.Dynamic] = js.undefined
  var textShadowRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  var textShadowColor: js.UndefOr[String] = js.undefined
  var textDecorationLine: js.UndefOr[String] = js.undefined
  var fontStyle: js.UndefOr[String] = js.undefined
  var textAlign: js.UndefOr[String] = js.undefined
  var textAlignVertical: js.UndefOr[String] = js.undefined
  var lineBreakMode: js.UndefOr[String] = js.undefined
  var writingDirection: js.UndefOr[String] = js.undefined
  var fontWeight: js.UndefOr[String] = js.undefined
  var backgroundColor: js.UndefOr[String] = js.undefined
  var borderColor: js.UndefOr[String] = js.undefined
  var tintColor: js.UndefOr[String] = js.undefined
  var overlayColor: js.UndefOr[String] = js.undefined
  var borderRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  var opacity: js.UndefOr[Double | AnimatedValue] = js.undefined
  var resizeMode: js.UndefOr[String] = js.undefined
  var aspectRatio: js.UndefOr[Double] = js.undefined
  var borderBottomColor: js.UndefOr[String] = js.undefined
  var borderLeftColor: js.UndefOr[String] = js.undefined
  var borderRightColor: js.UndefOr[String] = js.undefined
  var borderTopColor: js.UndefOr[String] = js.undefined
  var borderStyle: js.UndefOr[String] = js.undefined
  var rotation: js.UndefOr[Double | AnimatedValue] = js.undefined
  var scaleX: js.UndefOr[Double | AnimatedValue] = js.undefined
  var scaleY: js.UndefOr[Double | AnimatedValue] = js.undefined
  var shadowOpacity: js.UndefOr[Double | AnimatedValue] = js.undefined
  var shadowRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  var translateX: js.UndefOr[Double | AnimatedValue] = js.undefined
  var translateY: js.UndefOr[Double | AnimatedValue] = js.undefined
  var elevation: js.UndefOr[Double | AnimatedValue] = js.undefined
  var shadowColor: js.UndefOr[String] = js.undefined
  var shadowOffset: js.UndefOr[js.Object] = js.undefined
  var transformMatrix: js.UndefOr[js.Array[Double]] = js.undefined
  var borderTopLeftRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  var borderTopRightRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  var borderBottomLeftRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  var borderBottomRightRadius: js.UndefOr[Double | AnimatedValue] =
    js.undefined
  var transform: js.UndefOr[js.Array[js.Dynamic]] = js.undefined
}

@ScalaJSDefined
trait UniversalStyleVal extends js.Object {
  val flex: js.UndefOr[Double | AnimatedValue] = js.undefined
  val flexBasis: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  val flexShrink: js.UndefOr[Double | AnimatedValue] = js.undefined
  val flexGrow: js.UndefOr[Double | AnimatedValue] = js.undefined
  val borderBottomWidth: js.UndefOr[Double | AnimatedValue] = js.undefined
  val borderLeftWidth: js.UndefOr[Double | AnimatedValue] = js.undefined
  val borderRightWidth: js.UndefOr[Double | AnimatedValue] = js.undefined
  val borderTopWidth: js.UndefOr[Double | AnimatedValue] = js.undefined
  val borderWidth: js.UndefOr[Double | AnimatedValue] = js.undefined
  val bottom: js.UndefOr[Double | AnimatedValue] = js.undefined
  val height: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  val left: js.UndefOr[Double | AnimatedValue] = js.undefined
  val margin: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  val marginBottom: js.UndefOr[Double | AnimatedValue] = js.undefined
  val marginHorizontal: js.UndefOr[Double | AnimatedValue] = js.undefined
  val marginLeft: js.UndefOr[Double | AnimatedValue] = js.undefined
  val marginRight: js.UndefOr[Double | AnimatedValue] = js.undefined
  val marginTop: js.UndefOr[Double | AnimatedValue] = js.undefined
  val marginVertical: js.UndefOr[Double | AnimatedValue] = js.undefined
  val maxHeight: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  val maxWidth: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  val minHeight: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  val minWidth: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  val padding: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  val paddingBottom: js.UndefOr[Double | AnimatedValue] = js.undefined
  val paddingHorizontal: js.UndefOr[Double | AnimatedValue] = js.undefined
  val paddingLeft: js.UndefOr[Double | AnimatedValue] = js.undefined
  val paddingRight: js.UndefOr[Double | AnimatedValue] = js.undefined
  val paddingTop: js.UndefOr[Double | AnimatedValue] = js.undefined
  val paddingVertical: js.UndefOr[Double | AnimatedValue] = js.undefined
  val right: js.UndefOr[Double | AnimatedValue] = js.undefined
  val top: js.UndefOr[Double | AnimatedValue] = js.undefined
  val width: js.UndefOr[Double | AnimatedValue | String] = js.undefined
  val zIndex: js.UndefOr[Double | AnimatedValue] = js.undefined
  val letterSpacing: js.UndefOr[Double | AnimatedValue] = js.undefined
  val overflow: js.UndefOr[String] = js.undefined
  val position: js.UndefOr[String] = js.undefined
  val flexDirection: js.UndefOr[String] = js.undefined
  val flexWrap: js.UndefOr[String] = js.undefined
  val alignItems: js.UndefOr[String] = js.undefined
  val alignSelf: js.UndefOr[String] = js.undefined
  val justifyContent: js.UndefOr[String] = js.undefined
  val color: js.UndefOr[String] = js.undefined
  val containerBackgroundColor: js.UndefOr[String] = js.undefined
  val fontFamily: js.UndefOr[String] = js.undefined
  val fontSize: js.UndefOr[Double | AnimatedValue] = js.undefined
  val lineHeight: js.UndefOr[Double | AnimatedValue] = js.undefined
  val textShadowOffset: js.UndefOr[js.Dynamic] = js.undefined
  val textShadowRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  val textShadowColor: js.UndefOr[String] = js.undefined
  val textDecorationLine: js.UndefOr[String] = js.undefined
  val fontStyle: js.UndefOr[String] = js.undefined
  val textAlign: js.UndefOr[String] = js.undefined
  val textAlignVertical: js.UndefOr[String] = js.undefined
  val lineBreakMode: js.UndefOr[String] = js.undefined
  val writingDirection: js.UndefOr[String] = js.undefined
  val fontWeight: js.UndefOr[String] = js.undefined
  val backgroundColor: js.UndefOr[String] = js.undefined
  val borderColor: js.UndefOr[String] = js.undefined
  val tintColor: js.UndefOr[String] = js.undefined
  val overlayColor: js.UndefOr[String] = js.undefined
  val borderRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  val opacity: js.UndefOr[Double | AnimatedValue] = js.undefined
  val resizeMode: js.UndefOr[String] = js.undefined
  val aspectRatio: js.UndefOr[Double] = js.undefined
  val borderBottomColor: js.UndefOr[String] = js.undefined
  val borderLeftColor: js.UndefOr[String] = js.undefined
  val borderRightColor: js.UndefOr[String] = js.undefined
  val borderTopColor: js.UndefOr[String] = js.undefined
  val borderStyle: js.UndefOr[String] = js.undefined
  val rotation: js.UndefOr[Double | AnimatedValue] = js.undefined
  val scaleX: js.UndefOr[Double | AnimatedValue] = js.undefined
  val scaleY: js.UndefOr[Double | AnimatedValue] = js.undefined
  val shadowOpacity: js.UndefOr[Double | AnimatedValue] = js.undefined
  val shadowRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  val translateX: js.UndefOr[Double | AnimatedValue] = js.undefined
  val translateY: js.UndefOr[Double | AnimatedValue] = js.undefined
  val elevation: js.UndefOr[Double | AnimatedValue] = js.undefined
  val shadowColor: js.UndefOr[String] = js.undefined
  val shadowOffset: js.UndefOr[js.Object] = js.undefined
  val transformMatrix: js.UndefOr[js.Array[Double]] = js.undefined
  val borderTopLeftRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  val borderTopRightRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  val borderBottomLeftRadius: js.UndefOr[Double | AnimatedValue] = js.undefined
  val borderBottomRightRadius: js.UndefOr[Double | AnimatedValue] =
    js.undefined
  val transform: js.UndefOr[js.Array[js.Dynamic]] = js.undefined
}
